# Generated by Django 5.2.15 on 2026-06-19 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_prompt_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('token_prefix', models.CharField(max_length=12)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_tokens', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Widget token',
                'verbose_name_plural': 'Widget tokens',
                'ordering': ('-created_at',),
            },
        ),
    ]
