# Generated by Django 5.2.15 on 2026-06-21 07:17

import django.db.models.deletion
import workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_widgettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=workspaces.models.workspace_document_upload_to)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Обробка'), ('ready', 'Готовий'), ('failed', 'Помилка')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Документ workspace',
                'verbose_name_plural': 'Документи workspace',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_chunks', to='workspaces.workspace')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='workspaces.workspacedocument')),
            ],
            options={
                'verbose_name': 'Фрагмент документа',
                'verbose_name_plural': 'Фрагменти документів',
                'ordering': ('document', 'chunk_index'),
                'indexes': [models.Index(fields=['workspace'], name='workspaces__workspa_2059c0_idx')],
            },
        ),
    ]
