# Generated by Django 5.2.16 on 2026-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_widgettoken_openedx_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='meilisearch_course_id',
            field=models.CharField(blank=True, default='', help_text='Фільтр course-v1:... для courseware_content', max_length=255),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='meilisearch_indexes',
            field=models.JSONField(blank=True, default=list, help_text='Суфікси індексів (course_info) або повні UID (tutor_course_info)'),
        ),
    ]
